-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR, 
    TO_NUMBER(lTRIM(TO_CHAR(SALES_DATE,'MM'),'0')) AS MONTH, 
    GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO A JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_NUMBER(lTRIM(TO_CHAR(SALES_DATE,'MM'),'0')), GENDER
ORDER BY YEAR, MONTH, GENDER ASC