-- 코드를 입력하세요
SELECT A.MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A ,REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID AND 
    A.MEMBER_ID IN
    (SELECT MEMBER_ID
     FROM
   (SELECT MEMBER_ID, COUNT(REVIEW_TEXT) 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_TEXT) DESC)
    WHERE ROWNUM <= 1
    )
ORDER BY REVIEW_DATE, REVIEW_TEXT 
   