-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM AUTHOR A JOIN BOOK B 
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN (SELECT BOOK_ID,SUM(SALES) AS SALES, SALES_DATE
     FROM BOOK_SALES 
     GROUP BY BOOK_ID,SALES_DATE) C
ON B.BOOK_ID = C.BOOK_ID
WHERE TO_CHAR(C.SALES_DATE,'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC
