-- 코드를 입력하세요
SELECT B.TIME AS HOUR,NVL(COUNT(ANIMAL_ID),0) AS COUNT
FROM ANIMAL_OUTS A RIGHT OUTER JOIN 
(SELECT LEVEL-1 AS TIME FROM DUAL CONNECT BY LEVEL <= 24) B
ON TO_NUMBER(TO_CHAR(A.DATETIME,'HH24')) = B.TIME
GROUP BY B.TIME
ORDER BY 1


